/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tvmanagementsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author gupta
 */
public class addprogram extends javax.swing.JFrame {

    /**
     * Creates new form addprogram
     */
    public addprogram() {
        initComponents();
        moviestart.setVisible(false);
        moviestarttime.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        showname121 = new javax.swing.JLabel();
        shownametext = new javax.swing.JTextField();
        showname122 = new javax.swing.JLabel();
        showtype = new javax.swing.JComboBox<>();
        showname123 = new javax.swing.JLabel();
        time = new javax.swing.JComboBox<>();
        Add = new javax.swing.JButton();
        mainmenu = new javax.swing.JButton();
        moviestart = new javax.swing.JLabel();
        moviestarttime = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Add Program");

        showname121.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        showname121.setText("Show Name");

        showname122.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        showname122.setText("Show Category");

        showtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Show", "News", "Movie" }));
        showtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showtypeActionPerformed(evt);
            }
        });

        showname123.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        showname123.setText("Start Time");

        time.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1:00", "2:00", "3:00", "4:00", "5:00", "6:00" }));

        Add.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Add.setText("Add Program");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        mainmenu.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        mainmenu.setText("Main Menu");
        mainmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainmenuActionPerformed(evt);
            }
        });

        moviestart.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        moviestart.setText("Movie start time");

        moviestarttime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1:00", "2:00", "3:00" }));
        moviestarttime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moviestarttimeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(392, 392, 392)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(showname121, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(showname122, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(showname123, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(moviestart, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(162, 162, 162)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(showtype, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(shownametext, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                            .addComponent(time, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(moviestarttime, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(332, 332, 332))
            .addGroup(layout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112)
                .addComponent(mainmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showname121, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shownametext, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showname122, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showtype, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(showname123, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(time))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(moviestart, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(moviestarttime))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
      
        
        String showname=shownametext.getText();
        String type=showtype.getSelectedItem().toString();
        String starttime=time.getSelectedItem().toString();
        String duration;
        
       if(type.equalsIgnoreCase("movie")==true)
       {
           duration="210";
           starttime=moviestarttime.getSelectedItem().toString();
       }
       else
           duration="60";
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            String dbURL = "jdbc:mysql://localhost:3306/tv";
             Connection dbCon = null;
       
        ResultSet rs = null;
        
        
        String insertprogram="insert into programs values('"+showname+"','"+type+"','"+starttime+"','"+duration+"');";
        dbCon = DriverManager.getConnection(dbURL, "root","kapil" );
        Statement stmt=null;
        stmt = dbCon.createStatement();
        rs = stmt.executeQuery("select * from programs where starttime='"+starttime+"';");
        int x=0;
        int flag = -1;
        while(rs.next())
        {
            x = 1;
            if(rs.getString("category").equalsIgnoreCase("movie"))
                flag = 1;
        }
        if(x==1&&type.equalsIgnoreCase("movie")==false)
        {
            JOptionPane.showMessageDialog(null,"Timing not available");
            
        }
        else if(x==1 && flag == 1)
            JOptionPane.showMessageDialog(null,"Timing not available");
        else
        {
        stmt.executeUpdate(insertprogram);
        JOptionPane.showMessageDialog(null,"Program added successfully");
        }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(addprogram.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(addprogram.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AddActionPerformed

    private void mainmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainmenuActionPerformed
         this.setVisible(false);
         (new programmanager()).setVisible(true);
    }//GEN-LAST:event_mainmenuActionPerformed

    private void showtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showtypeActionPerformed
        
        if(showtype.getSelectedIndex()==2)
        {
                moviestart.setVisible(true);
                moviestarttime.setVisible(true);
                time.setVisible(false);
                showname123.setVisible(false);
        }
        else
        {
                moviestart.setVisible(false);
                moviestarttime.setVisible(false);
                time.setVisible(true);
        }
    }//GEN-LAST:event_showtypeActionPerformed

    private void moviestarttimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moviestarttimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moviestarttimeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addprogram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addprogram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addprogram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addprogram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addprogram().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton mainmenu;
    private javax.swing.JLabel moviestart;
    private javax.swing.JComboBox<String> moviestarttime;
    private javax.swing.JLabel showname121;
    private javax.swing.JLabel showname122;
    private javax.swing.JLabel showname123;
    private javax.swing.JTextField shownametext;
    private javax.swing.JComboBox<String> showtype;
    private javax.swing.JComboBox<String> time;
    // End of variables declaration//GEN-END:variables
}
